Fixed x overflow in mobile view
NIAEFEUP/nijobs-fe pull request #136
Opened 2021-09-24 15:27 UTC by TiagooGomess

Closes #135

2021-09-27 13:47 UTC, TiagooGomess commented
I don't know if this is the better approach to fix this problem, I need some feedback.

2021-09-27 17:59 UTC, imnotteixeira commented
This is a hack, please find the element that is triggering the overflow and fix that instead

2021-09-27 18:05 UTC, imnotteixeira commented
> This is a hack, please find the element that is triggering the overflow and fix that instead

From what I could gather, it's the Grid from ProductDescription

2021-09-27 18:07 UTC, imnotteixeira commented
The fix is to remove the `spacing={10}` from the outer Grid container, but that will make the items be closer together, so you need to add padding to them specifically, to maintain the visual aspect

2021-09-27 20:41 UTC, imnotteixeira requested changes

2021-09-27 20:41 UTC, imnotteixeira commented on src/components/HomePage/ProductPlacementArea/productDescriptionStyles.js
> +            padding: isMobile ? "40px 0" : "40px 40px",
Use theme.spacing instead of hardcoded 40px

2021-10-01 20:44 UTC, imnotteixeira approved these changes

2021-10-01 21:17 UTC, merged