Unclear unexpected error in enable offer button in view page as a company
NIAEFEUP/nijobs-fe pull request #157
Opened 2022-01-15 17:52 UTC by kiko-serra

Closes #139

2022-01-15 18:05 UTC, TiagooGomess requested changes
To solve these linting issues automatically, you should install and enable eslint in your VSCode.

2022-01-15 18:05 UTC, TiagooGomess commented on src/utils/offer/OfferUtils.js
> +    "max-concurrent-offers-reached:5": "You cannot have more than 5 concurrent visible offers."
```suggestion
    "max-concurrent-offers-reached:5": "You cannot have more than 5 concurrent visible offers.",
```

2022-01-15 18:05 UTC, TiagooGomess commented on src/utils/offer/OfferUtils.js
> +
```suggestion

```

2022-01-22 10:44 UTC, DoStini requested changes

2022-01-22 10:44 UTC, DoStini commented on src/utils/offer/OfferUtils.js
> +    "max-concurrent-offers-reached:5": "You cannot have more than 5 concurrent visible offers.",
The solution is not as simple as this, you shouldn't hard code the value `5`. 
You can take a look at how it's being done in [other places](https://github.com/NIAEFEUP/nijobs-fe/blob/d6d0d2fd0f08c6600857259112cc6dc11ea27067/src/components/Offers/New/CreateOfferUtils.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L51-L55).

2022-03-16 18:13 UTC, TiagooGomess commented
Closing this because it's a duplicate of #194

2022-03-16 18:13 UTC, closed without merging