Draft:Feature/tables mobile view
NIAEFEUP/nijobs-fe pull request #165
Opened 2022-01-30 01:34 UTC by monkin77

2022-02-25 18:53 UTC, monkin77 commented
![image](https://user-images.githubusercontent.com/28673635/155771577-0a37e326-1e92-4b51-8c0b-9bb4af019c38.png)
![image](https://user-images.githubusercontent.com/28673635/155771673-2cc11db0-7d2e-4f31-b25a-b2c77176fcfd.png)

2022-03-12 20:35 UTC, monkin77 commented
> Lots of extra commits eyes
> 
> Apart from that, is the table footer having a horizontal scroll issue? Looks like something's missing when looking at the screenshots

I'll take care of that :sweat_smile: . Regarding the footer, I've already fixed it but the screenshots aren't updated

2022-03-13 16:42 UTC, TiagooGomess requested changes

2022-03-13 16:42 UTC, TiagooGomess commented on src/components/Company/Offers/Manage/CompanyOffersManagementWidget.js
> +/* const RowActions = ({ row }) => {
Remove commented code.

2022-03-13 16:42 UTC, TiagooGomess commented on src/components/Company/Offers/Manage/CompanyOffersManagementWidget.js
> +            ) : (
```suggestion
            isMobile && (
```

2022-03-15 08:08 UTC, TiagooGomess approved these changes

2022-03-15 14:12 UTC, merged