Changed the logout button order
NIAEFEUP/nijobs-fe pull request #193
Opened 2022-03-14 16:56 UTC by dfneves19

Changed the logout button order so it appears last.

2022-03-16 18:17 UTC, TiagooGomess approved these changes

2022-03-16 18:17 UTC, TiagooGomess commented
You should rebase with develop before merging

2022-03-16 18:24 UTC, TiagooGomess requested changes

2022-03-16 18:24 UTC, TiagooGomess commented on src/components/Navbar/UserMenu.js
>              </Typography>
```suggestion
            </Typography>
            {sessionData?.company && <Divider className={classes.divider} />}
```

2022-03-16 18:24 UTC, TiagooGomess commented on src/components/Navbar/UserMenu.js
>              </Typography>
I'm sorry for changing my review; I only saw this after approving the PR.

2022-03-20 00:43 UTC, DoStini commented
The divider is not yet fixed isn't it? @dfneves19 

![image](https://user-images.githubusercontent.com/23351316/159143248-d8a67791-f479-447e-9d06-511636d44845.png)

2022-03-20 00:47 UTC, DoStini requested changes

2022-03-20 00:47 UTC, DoStini commented on src/components/Navbar/UserMenu.js
> +                <Divider className={classes.divider} />
In order to fix the divider not being the same width as the top one, I think you need to remove this `classes.divider`. @TiagooGomess

2022-03-28 11:29 UTC, dfneves19 commented
while logged in as a company the dividers are exactly the same, but when logged in as admin the logout divider is still a little deviated to the left.

2022-09-12 09:18 UTC, CarlosMealha commented
So I fixed the divider problem with a trivial solution, adding a break statement just to know if it's an admin or a company account authenticated, and then I duplicated the style, just changing the width percentage.  What do you guys think?

2022-09-12 21:11 UTC, Naapperas commented
@DoStini please review this PR (since you requested changes previously, also because I would appreciate a second opinion)

2022-09-14 17:33 UTC, CarlosMealha commented
> @DoStini please review this PR (since you requested changes previously, also because I would appreciate a second opinion)

I think this would fix the problem
![image](https://user-images.githubusercontent.com/79020867/190223594-3d3f13c1-bd9b-45f3-88f2-80165c813d9e.png)

2022-09-17 12:09 UTC, Naapperas approved these changes
Rebase

2022-09-25 21:22 UTC, BrunoRosendo commented
@CarlosMealha This was already approved but it needs to be rebased. Shouldn't take too long

2022-09-27 10:50 UTC, CarlosMealha commented
> @CarlosMealha This was already approved but it needs to be rebased. Shouldn't take too long

Okay, it's already done, please aprove it.

2022-10-02 17:54 UTC, merged