Feature/recover password
NIAEFEUP/nijobs-fe pull request #260
Opened 2022-08-17 22:02 UTC by DoStini

2022-08-19 12:09 UTC, Naapperas commented
Can you post some prints of the feature ?

2022-08-20 19:05 UTC, DoStini commented
> 

There you go

https://user-images.githubusercontent.com/23351316/185762573-d9545688-5880-40dd-b240-c38cb41d1526.mov

2022-08-20 21:07 UTC, BrunoRosendo commented
> > 
> 
> There you go
> Screen.Recording.2022-08-20.at.21.01.44.mov

From watching the video, the FE flow doesn't seem to match the BE implementation. I think this would make sense if the users received a simple short code. I don't think it makes sense for them to past this huge token into the field. I prefer the flow where they just click on the link, or instead simplify the token somehow (I'm not sure if that could have security concerns)

2022-08-20 21:47 UTC, DoStini commented
> 

The BE needs to be updated to follow this login. I will see if the code can be shortened

2022-08-20 22:06 UTC, Naapperas commented
I'm with Bruno, pasting the link could be cumbersome, if we somehow could just click the link and proceed with the rest of the flow we should do that.

2022-08-22 07:44 UTC, DoStini commented
> I'm with Bruno, pasting the link could be cumbersome, if we somehow could just click the link and proceed with the rest of the flow we should do that.

I'll try a different approach, when clicking on the link, redirect with modal opened on the finish part.

> Also, the transition from "new password" to "login" seems weird but that might be just me

How so? I think it makes sense to redirect to the login "page"

2022-08-31 23:03 UTC, DoStini commented
https://user-images.githubusercontent.com/23351316/187799892-4a240ed5-b663-406c-b657-bdfde7de0360.mov

2022-09-10 04:12 UTC, Naapperas requested changes

2022-09-10 04:12 UTC, Naapperas commented on src/pages/HomePage.js
> +            dispatch(toggleAuthModal(2));
This `2` can cause confusion being left as is (I had to look at the definition of the action function to understand it was a page number). Maybe change the action function name or turn this into a constant.

2022-09-10 04:12 UTC, Naapperas commented on src/components/Navbar/Auth/PasswordRecoveryFinishForm.spec.js
> +            });
Couldn't these have been in the same `act(...)` call ?

2022-09-10 04:12 UTC, Naapperas commented on src/components/Navbar/Auth/PasswordRecoveryFinishForm.spec.js
> +            });
I pointed it out here but there are other places where this pattern is repeated.

2022-11-04 18:29 UTC, Naapperas commented
@DoStini is this ready for review ?

2022-11-05 01:03 UTC, Naapperas commented on src/components/Navbar/Auth/PasswordRecoveryFinishForm.spec.js
> +
In this function why did you mock `useParams` ? I understand that this and other `react-router` functions are not defined in JSDom but if you are using `BrowserRouter`s to wrap your test components the mock should not be necessary, unless I'm overlooking something important.

2022-11-05 01:07 UTC, Naapperas approved these changes

2022-11-08 14:41 UTC, merged