Fixed incorrect offeSearch state after returning to Home Page
NIAEFEUP/nijobs-fe pull request #284
Opened 2022-12-05 18:36 UTC by Naapperas

2022-12-05 20:40 UTC, Naapperas commented
The build is failing because of the code coverage percentage, I still need to find where this can be improved but the tests themselves are passing.

2022-12-06 15:45 UTC, BrunoRosendo requested changes

2022-12-06 15:45 UTC, BrunoRosendo commented on src/components/HomePage/SearchArea/AdvancedSearch/AdvancedSearchDesktop.spec.js
> +                        setSearchValue={() => { }}
Refactor to use default values instead of specifying in every call

2022-12-07 16:37 UTC, DoStini approved these changes
LGTM :rocket:

2022-12-07 17:49 UTC, merged