fixed text-cropping in user accounts email
NIAEFEUP/nijobs-fe pull request #327
Opened 2023-11-22 19:36 UTC by jose-carlos-sousa

I tried to fix text cropping using ellipsis
![Screenshot from 2023-11-20 01-11-00](https://github.com/NIAEFEUP/nijobs-fe/assets/139002032/0b4adef2-3c29-48f4-8d34-db68138cba16)

2023-12-06 15:43 UTC, Naapperas requested changes

2023-12-06 15:43 UTC, Naapperas commented on Programs and Features.
What is this file @jose-carlos-sousa?

2024-01-05 23:33 UTC, Naapperas commented on .env
Why was this file changed?

2024-01-06 18:23 UTC, jose-carlos-sousa commented on .env
It shouldn't have been ,I have changed the port to the original one now

2024-01-07 20:35 UTC, Naapperas approved these changes

2024-01-07 20:35 UTC, Naapperas commented
Good job. :shipit:

2024-01-17 19:12 UTC, FranciscoCardoso913 approved these changes
Looks good to merge :)

2024-03-06 17:49 UTC, merged