Feature/beautify error page
NIAEFEUP/nijobs-fe pull request #77
Opened 2021-03-01 17:24 UTC by TiagooGomess

### Current design:
Not found page:
![Screenshot from 2021-03-01 17-15-37](https://user-images.githubusercontent.com/50210213/109533648-5d1ed080-7ab2-11eb-93a9-dfb6e758a4bc.png)

Error page:
![Screenshot from 2021-03-01 17-23-30](https://user-images.githubusercontent.com/50210213/109534090-ddddcc80-7ab2-11eb-9bee-82ebf59a8613.png)

Closes #58

2021-03-03 15:05 UTC, imnotteixeira requested changes

2021-03-03 15:05 UTC, imnotteixeira commented on src/pages/ErrorPage.js
> +    <ErrorComponent Message={"Something is wrong in the backstage. :("}/>
The old message was just a placeholder. Please change to something more formal like "Something unexpected prevented us from fulfilling your request. Please try again later, and if the problem persists, contact us at ni@aefeup.pt (make this an actual `mailto` link)"

2021-03-03 15:05 UTC, imnotteixeira commented on src/pages/NotFound.js
> +            <ErrorComponent Message={"Sorry, no page could be found at this address (404)"}/>
If you add a title prop to the error component, you can keep it generic and pass a different title and message for 404 and unexpected errors

2021-03-03 15:05 UTC, imnotteixeira commented on src/pages/NotFound.spec.js
> +            <ErrorComponent Message={errorMessage}/>,
In order to test the Not Found page, you should not render its contents, but the page itself, and assert that the contents are as expected. Change the component to just the <NotFound> and assert that the error message is whatever you'll put on the component above. If you add the title, add here the assertion that the title is present as well.

Finally, add a similar test for the error page as well

2021-03-07 17:04 UTC, TiagooGomess commented
## Page not found:
![Screenshot from 2021-03-07 16-41-37](https://user-images.githubusercontent.com/50210213/110248051-212eb400-7f67-11eb-9a2d-178a01d366e4.png)

## Error page:
![Screenshot from 2021-03-07 16-43-51](https://user-images.githubusercontent.com/50210213/110248045-1a07a600-7f67-11eb-8286-c57f7b4d62e2.png)

2021-03-12 14:37 UTC, imnotteixeira requested changes
On the mobile version, the homepage icon (button in the navbar) should be white. That happens because it is not taking into account the forceDesktopLayout. Only when forceDesktopLayout=false it should be the dark red, since the background will be the white from the dialog.

Regarding the ErrorComponent, the text should be left aligned (both title and content)

Finally, you should unstage the package*.json -related changes and drop irrelevant commits, to avoid conflicts in the future, but regarding this we can sync "offline"

2021-03-14 14:52 UTC, TiagooGomess commented
## Desktop view:
![Screenshot from 2021-03-14 14-50-38](https://user-images.githubusercontent.com/50210213/111072955-b7695980-84d4-11eb-9ef4-f1f93f09a7f6.png)

## Mobile view:
![Screenshot from 2021-03-14 14-50-50](https://user-images.githubusercontent.com/50210213/111072953-b6d0c300-84d4-11eb-86d8-003dfdb6e692.png)

2021-03-17 18:59 UTC, imnotteixeira requested changes

2021-03-17 18:59 UTC, imnotteixeira commented on src/components/Errors/ErrorComponent.js
> +                <Link color="secondary" href="mailto:ni@aefeup.pt">
```suggestion
                <Link color="secondary" href={`mailto:${email}`}>
```

2021-03-17 18:59 UTC, imnotteixeira commented on src/components/Errors/ErrorComponent.js
> +    return <Typography />;
return null instead

2021-03-17 19:32 UTC, imnotteixeira approved these changes

2021-03-17 19:38 UTC, merged